---
title:               alexander bakus
tagline:             happy SAAS warrior  
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Alex Bakus
staticpost:          flic-ou-voyou
twitter:             alexanderbak
linkedIn:            alexanderbakus
github:              alexbakus
email:               alexanderbak@gmail.com
google_analytics_id: UA-25408022-1
hittail_id:          102163
